# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main
            - development

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Docker Login
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{secrets.DOCKER_USER}}
                  password: ${{secrets.DOCKER_TOKEN}}

            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v1.6.0
              with:
                  version: latest

            - name: Build & Deploy Dev
              if: github.ref == 'refs/heads/development'
              run: |
                  docker buildx build \
                    --platform linux/arm64 \
                    --build-arg NODE_ENV=production \
                    --tag ${{secrets.DOCKER_USER}}/quick-dashboard-api:dev-latest \
                    --push \
                    ./

            - name: Build & Deploy Prod
              if: github.ref == 'refs/heads/main'
              run: |
                  docker buildx build \
                    --platform linux/arm64 \
                    --build-arg NODE_ENV=production \
                    --tag ${{secrets.DOCKER_USER}}/quick-dashboard-api:latest \
                    --push \
                    ./
